# Generated by Django 6.0.7 on 2026-07-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('movies', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to='movies.movie'),
        ),
    ]
